import 'package:social_media/models/video_list.dart';

class DemoData {
  static final VideoList list = VideoList(
        status: 1,
        message: "Success",
        more: 0,
        offset: 0,
        limit: "1000",
        count: 36,
        data: [
          Data(
            image: "https://cpxphp8.covetus.com/youtubeapp/public/uploads/videos/1678433530youtubeDefaultImgmaxresdefault.jpg",
            id: 4,
            title: "ENGLISH SPEECH | SACHIN TENDULKAR: Be the Best (English Subtitles)",
            videoSlug: "english-speech-sachin-tendulkar-be-the-best-english-subtitles--3167843",
            message: "<p>Learn English with Sachin Tendulkar. BMW Melbourne hosted a memorable night event interview with Sachin Tendulkar, the former Indian cricketer widely regarded as one of the greatest batsmen of all time.</p>\r\n\r\n<p>Sachin Ramesh Tendulkar is a former international cricketer of India who served as captain of the Indian national team. He is widely regarded as one of the greatest batsmen in the history of cricket.</p>\r\n\r\n<p>In this speech, he also quotes: &quot;I was only 16 then when I went to the bathroom, and I cried. I looked at myself in the mirror, said, this level of cricket is not for you. You&#39;re not good enough to do all this. Fortunately, I got about six days in between. I never doubted my ability, but in the first match, I thought it was my first and the last one.&quot;</p>\r\n\r\n<p>&ndash; English subtitles make it even more enjoyable. Watch, learn, and share &ndash;</p>\r\n\r\n<p>✅ Get the full transcript and audio of this speech FREE on our website:</p>\r\n\r\n<p>https://www.englishspeecheschannel.com/english-speeches/sachin-tendulkar-speech</p>\r\n\r\n<p>✅ Learn English with Speeches:</p>\r\n\r\n<p>https://www.youtube.com/c/LearnEnglishwithSpeeches?sub_confirmation=1</p>\r\n\r\n<p>✅ Also, download our FREE English Ebooks:</p>\r\n\r\n<p>https://www.englishspeecheschannel.com/free-english-ebooks</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>✅ Get Your FREE English Lessons Right Now:</p>\r\n\r\n<p>http://bit.ly/englishspeeches</p>\r\n\r\n<p>✅ Have you seen our NEW project?</p>\r\n\r\n<p>https://www.youtube.com/c/BiographyTimeline</p>\r\n\r\n<p>✅ Become a channel member. Sponsor English Speeches (includes exclusive rewards) &rarr; https://www.youtube.com/englishspeeches/join</p>\r\n\r\n<p>Subscribe to our Telegram Channel:</p>\r\n\r\n<p>✅ https://t.me/EnSpeeches</p>\r\n\r\n<p>Follow us on Social Media:</p>\r\n\r\n<p>👉🏽 Instagram: englishspeeches</p>\r\n\r\n<p>👉🏽 Facebook: englishspeeches</p>\r\n\r\n<p>👉🏽 Twitter: englishspeeches</p>\r\n\r\n<p>👉🏽 TikTok: englishspeeches</p>\r\n\r\n<p>All content on our website is totally FREE.</p>\r\n\r\n<p>The only thing we ask is: Please! SUBSCRIBE to our Channel:</p>\r\n\r\n<p>🙏🏻 https://www.youtube.com/englishspeeches?sub_confirmation=1</p>\r\n\r\n<p>❤️ Thank you for watching!</p>\r\n\r\n<p>#EnglishSpeeches</p>\r\n\r\n<p>#EnglishSubtitles</p>\r\n\r\n<p>#LearnEnglish</p>\r\n\r\n<p>#EnglishSpeech</p>\r\n\r\n<p>#SachinTendulkarSpeech</p>\r\n\r\n<p>Link to the original video:</p>\r\n\r\n<p>https://youtu.be/PzpjF5DSkSc</p>\r\n\r\n<p>We use this video for educational purposes. Thank you for making this Speech possible.</p>\r\n\r\n<p>FAIR-USE COPYRIGHT DISCLAIMER</p>\r\n\r\n<p>* Copyright Disclaimer Under Section 107 of the Copyright Act 1976, allowance is made for &quot;fair use&quot; for purposes such as criticism, commenting, news reporting, teaching, scholarship, and research. Fair use is a use permitted by copyright statute that might otherwise be infringing. Non-profit, educational or personal use tips the balance in favor of fair use.</p>\r\n\r\n<p>1)This video has no negative impact on the original works (It would actually be positive for them)</p>\r\n\r\n<p>2)This video is also for teaching purposes.</p>\r\n\r\n<p>3)It is not transformative in nature.</p>\r\n\r\n<p>4)I only used bits and pieces of videos to get the point across where necessary.</p>\r\n\r\n<p>English Speeches does not own the rights to these video clips. They have, in accordance with fair use, been repurposed with the intent of educating and inspiring others. However, if any content owners would like their images removed, please contact us by email at contact@englishspeecheschannel.com</p>",
            userId: 6,
            parentCategoryId: 9,
            parentCategoryName: "Biography",
            subCategoryId: 19,
            subCategoryName: "Cricketer",
            childCategoryId: null,
            childCategoryName: "",
            videoUrl: "https://www.youtube.com/watch?v=AwA0Jnfj3ao",
            youtubeVideoId: "AwA0Jnfj3ao",
            videoDuration: "00:17:50",
            tags: "safd198yjmkkvz0189hystty, english, speech, english speech, english speeches by famous people, english speech for learning, english speeches with big subtitles, english speech with subtitles, english speech pratice, english speech videos, english speaking, speeches in english, learn english, Improve, Writing, Grammar, vocabulary, speaking, script, transcript, Sachin Tendulkar, Sachin Tendulkar Speech, Sachin Tendulkar Interview, Indian Accent, Cricket Player, Indian Cricket Player",
            videoPublishedDate: "2021-10-09 00:00:00",
              createdAt: "2023-03-10 07:32:10",
            isFavorite: 0,
            labelId: 0
          ),
          Data(
            image: "https://cpxphp8.covetus.com/youtubeapp/public/uploads/videos/1678435399youtubeDefaultImgmaxresdefault.jpg",
            id: 5,
            videoSlug: "baburao-ganpatrao-apte-hit-comedy-scene--4167843",
            title: "Baburao Ganpatrao Apte Hit Comedy Scene | परेश रावल की कॉमेडी | बाबूराव गणपतराव आप्टे कॉमेडी",
            message: "<p>Watch Baburao Ganpatrao Apte Hit Comedy Scene | परेश रावल की ज़बरदस्त कॉमेडी | बाबूराव गणपतराव आप्टे कॉमेडी</p>\r\n\r\n<p>Movie:- Hera Pheri (2000)</p>\r\n\r\n<p>Starcast:- Akshay Kumar, Sunil Shetty, Paresh Rawal, Tabu, Om Puri</p>\r\n\r\n<p>Directed by:- Priyadarshan</p>\r\n\r\n<p>Music by:- Anu Malik</p>\r\n\r\n<p>------------------------------------------------</p>\r\n\r\n<p>Enjoy and stay connected with us!!</p>\r\n\r\n<p>Subscribe to Goldmines Hindi:-</p>\r\n\r\n<p>https://goo.gl/97SvE2</p>\r\n\r\n<p>------------------------------------------------</p>",
            userId: 6,
            parentCategoryId: 2,
            parentCategoryName: "Comedy",
            subCategoryId: null,
            subCategoryName: "",
            childCategoryId: null,
            childCategoryName: "",
            videoUrl: "https://www.youtube.com/watch?v=5FXFnyRnl48",
            youtubeVideoId: "5FXFnyRnl48",
            videoDuration: "00:11:30",
            tags: "Goldmines Hindi, Goldmines movies, hindi movies 2019, परेश रावल की ज़बरदस्त कॉमेडी, बाबूराव गणपतराव आप्टे कॉमेडी, hera pheri comedy scenes, paresh rawal best comedy, paresh rawal best comedy scenes, bollywood comedy scenes, bollywood best comedy scenes, paresh rawal superhit comedy, baburao ganpatrao apte comedy, paresh rawal comedy, hera pheri akshay kumar comedy scenes, hera pheri akshay kumar sunil shetty paresh rawal, akshay kumar comedy scene, sunil shetty comedy scene",
            videoPublishedDate: "2019-09-21 00:00:00",
              createdAt: "2023-03-10 08:03:19",
            isFavorite: 0,
            labelId: 0
          ),
          Data(
            image: "https://cpxphp8.covetus.com/youtubeapp/public/uploads/videos/1678435472youtubeDefaultImgmaxresdefault.jpg",
            id: 6,
            title: "Kauwa Biryani Comedy King Vijay Raaz Best Comedy Hindi Movie | Bollywood Comedy Film",
            videoSlug: "kauwa-biryani-comedy-king-vijay-raaz-best-comedy-hindi-movie-bollywood-comedy-film-5167843",
            message: "<p>Subscribe: http://bit.ly/DRJRecordsSpecials</p>\r\n\r\n<p>Movie: Gali Gali Chor Hai</p>\r\n\r\n<p>Label: DRJ Records</p>\r\n\r\n<p>Welcome to DRJ Records Specials YouTube Channel, the #1 destination for premium entertainment videos. Enjoy the blockbuster in all languages Full movies, scenes, songs, &amp; more.</p>\r\n\r\n<p>(C) 2022 DRJ Records Industries Private Limited</p>\r\n\r\n<p>Like, Comment, and Share with your friends and family.</p>\r\n\r\n<p>Subscribe to DRJ Records Specials: http://bit.ly/DRJRecordsSpecials</p>\r\n\r\n<p>Facebook: http://www.facebook.com/drjrecords</p>\r\n\r\n<p>Twitter: http://www.twitter.com/drjrecords</p>\r\n\r\n<p>Instagram: http://www.instagram.com/drjrecords</p>",
            userId: 6,
            parentCategoryId: 2,
            parentCategoryName: "Comedy",
            subCategoryId: null,
            subCategoryName: "",
            childCategoryId: null,
            childCategoryName: "",
            videoUrl: "https://www.youtube.com/watch?v=l59ZFCO_RHQ",
            youtubeVideoId: "l59ZFCO_RHQ",
            videoDuration: "00:18:42",
            tags: "kauwa biryani comedy, vijay raaz comedy, vijay raj comedy, vijay raaz, best comedy vijay raaz hindi movie run, vijay raaz hindi movie run, comedy video, Kauwa Biryani, gali gali chor hai, comedy of vijay raaz, best comedy movies in hindi, best comedy, hindi comedy, love comedy movies, new comedy movie, kauwa biryani, run movie comedy, run movie spoof",
            videoPublishedDate: "2022-12-25 00:00:00",
              createdAt: "2023-03-10 08:04:32",
            isFavorite: 0,
            labelId: 0
          ),
          Data(
            image: "https://cpxphp8.covetus.com/youtubeapp/public/uploads/videos/1678435525youtubeDefaultImgmaxresdefault.jpg",
            id: 7,
            title: "हस्ते हस्ते कट जाये जिंदगी |  #WorldLaughterDay | Akshay Kumar - Paresh Rawal - Rajpal Yadav",
            videoSlug: "-worldlaughterday-akshay-kumar-paresh-rawal-rajpal-yadav-6167843",
            message: "<p>Enjoy World Laughter Day with the Best Hindi Comedy Scenes, compilation of the best comic scenes from one of the comedy films. It includes scenes of comedians like Johnny Lever, Paresh Rawal, Arshad Warsi, &amp; Akshay Kumar. Have a great time watching this hilarious compilation.</p>\r\n\r\n<p>1. Phir Hera Pheri</p>\r\n\r\n<p>2. Deewane Huye Paagal</p>\r\n\r\n<p>3. Welcome</p>\r\n\r\n<p>4. Dhol</p>\r\n\r\n<p>5. Khatta Meetha</p>\r\n\r\n<p>6. Bhagam Bhag</p>\r\n\r\n<p>7. Dulhe Raja</p>\r\n\r\n<p>8. Dhamaal</p>\r\n\r\n<p>हस्ते हस्ते कट जाये जिंदगी | #WorldLaughterDay | Akshay Kumar - Paresh Rawal - Rajpal Yadav</p>\r\n\r\n<p>#ComedyScenes #Comedy</p>\r\n\r\n<p>Johny Lever Superhit Comedy Scenes | Kader Khan Superhit Comedy Scenes | Kader Khan Comedy | Johny Lever comedy | Johny Lever Blockbuster Movie | Kader Khan Blockbuster Movie | Salman Khan Comedy Scenes| Johny Lever Comedy | Phir Hera Pheri Comedy Scenes | Paresh Rawal Comedy Scenes | Paresh Rawal Comedy Movie | Rajpal Yadav Comedy Scenes | Akshay Kumar Comedy Movie | Salman Khan Comedy Scenes</p>\r\n\r\n<p>SUBSCRIBE to http://www.youtube.com/subscription_center?add_user=indiancomedy</p>\r\n\r\n<p>Like, Comment and Share this funny video with your friends and family.</p>\r\n\r\n<p>Connect with us on:-</p>\r\n\r\n<p>Facebook -http://www.Facebook.com/ShemarooEnt</p>\r\n\r\n<p>Twitter http://Twitter.com/ShemarooEnt</p>\r\n\r\n<p>Google Plus - https://plus.google.com/+shemaroo</p>\r\n\r\n<p>Pinterest - http://pinterest.com/shemaroo</p>\r\n\r\n<p>Sign up for Free and get daily updates on New Videos, exclusive Web Shows, contests &amp; much more</p>\r\n\r\n<p>http://youtube.shemaroo.com/default.aspx</p>\r\n\r\n<p>Send us your feedback and suggestions at: connect@shemaroo.com</p>\r\n\r\n<p>For more Comedy Movies download the ShemarooMe app now and share it with your Friends and Family</p>\r\n\r\n<p>Download the app now and share it with all the asli fans</p>\r\n\r\n<p>Android: http://bit.ly/2K1lKfd</p>\r\n\r\n<p>iPhone: https://apple.co/2WGZGI7</p>\r\n\r\n<p>Give a missed call on 18002665151</p>\r\n\r\n<p>www.shemaroome.com</p>",
            userId: 6,
            parentCategoryId: 2,
            parentCategoryName: "Comedy",
            subCategoryId: null,
            subCategoryName: "",
            childCategoryId: null,
            childCategoryName: "",
            videoUrl: "https://www.youtube.com/watch?v=1TqKyb-g2cs",
            youtubeVideoId: "1TqKyb-g2cs",
            videoDuration: "00:31:14",
            tags: "rajpal yadav comedy, akshay kumar comedy movies, comedy movies, best movies to watch, bollywood movies, best movies 2020, phir hera pheri comedy scene, paresh rawal comedy, comedy scenes, rajpal yadav comedy scenes, awara paagal deewana comedy scenes, akshay kumar, comedy scenes hindi movies, comedy scenes hindi 2021, paresh rawal comedy movies full, phir hera pheri comedy scene johny lever, phir hera pheri comedy scene rajpal yadav, phir hera pheri comedy scenes johnny lever",
            videoPublishedDate: "2022-05-01 00:00:00",
              createdAt: "2023-03-10 08:05:25",
            isFavorite: 0,
            labelId: 0
          ),
        ]
    );
}